# Generated by Django 5.2.4 on 2025-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteNEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('miss_distance', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
