# Generated by Django 5.2.4 on 2025-07-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteneo',
            unique_together={('user_email', 'name')},
        ),
    ]
